// This file is automatically generated. Do not modify it manually.
import {type FirebaseOptions} from 'firebase/app';

// Your web app's Firebase configuration
// For Firebase JS SDK v7.20.0 and later, measurementId is optional
export const firebaseConfig = {
  "projectId": "studio-6072428518-2e28a",
  "appId": "1:34456202028:web:88053b973626717e9ada89",
  "apiKey": "AIzaSyAmbpO_3GIZ46AyvmAZNZMOXOB4qWA2kKg",
  "authDomain": "studio-6072428518-2e28a.firebaseapp.com",
  "storageBucket": "studio-6072428518-2e28a.appspot.com",
  "messagingSenderId": "34456202028"
} satisfies FirebaseOptions;
