// This file is automatically generated. Do not modify it manually.
import {getApp, getApps, initializeApp} from 'firebase/app';

import {firebaseConfig} from './config';

export * from './provider';
export * from './firestore/use-doc';
export * from './firestore/use-collection';

/**
 * Initializes the Firebase app.
 *
 * This function should be called before any other Firebase services are used.
 *
 * @returns The initialized Firebase app.
 */
export function initializeFirebase() {
  const app = getApps().length === 0 ? initializeApp(firebaseConfig) : getApp();

  return {app};
}
